/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.tsx"],
  theme: {
    extend: {
      colors: {
        // Palette CEP (Material 3, mode clair)
        "primary": "#005da9",
        "on-primary": "#ffffff",
        "primary-container": "#0076d3",
        "on-primary-container": "#fdfcff",
        "primary-fixed": "#d4e3ff",
        "primary-fixed-dim": "#a4c9ff",
        "on-primary-fixed": "#001c39",
        "on-primary-fixed-variant": "#004884",
        "surface": "#fef9ef",
        "surface-dim": "#ded9d1",
        "surface-bright": "#fef9ef",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f8f3ea",
        "surface-container": "#f3ede4",
        "surface-container-high": "#ede8df",
        "surface-container-highest": "#e7e2d9",
        "surface-variant": "#e7e2d9",
        "surface-tint": "#005fad",
        "on-surface": "#1d1c16",
        "on-surface-variant": "#414752",
        "on-background": "#1d1c16",
        "background": "#fef9ef",
        "inverse-surface": "#32302a",
        "inverse-on-surface": "#f5f0e7",
        "inverse-primary": "#a4c9ff",
        "secondary": "#5f5e5c",
        "on-secondary": "#ffffff",
        "secondary-container": "#e2dfdb",
        "secondary-fixed": "#e5e2de",
        "secondary-fixed-dim": "#c8c6c3",
        "on-secondary-fixed": "#1b1c1a",
        "on-secondary-fixed-variant": "#474744",
        "tertiary": "#904900",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#b55d00",
        "on-tertiary-container": "#fffbff",
        "tertiary-fixed": "#ffdcc5",
        "tertiary-fixed-dim": "#ffb783",
        "on-tertiary-fixed": "#301400",
        "on-tertiary-fixed-variant": "#703700",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "outline": "#717784",
        "outline-variant": "#c0c7d4",
        "status-active-bg": "#e6f4ea",
        "status-active-text": "#137333",
        "vote-ok-bg": "#dcfce7",
        "vote-ok-text": "#166534",
        "vote-no-bg": "#f3f4f6",
        "vote-no-text": "#1f2937",
        "vote-blanc-bg": "#fef9c3",
        "vote-blanc-text": "#854d0e",
      },
      fontSize: {
        "headline-lg": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-sm": ["16px", { "lineHeight": "24px", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-sm": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
        "label-md": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "label-sm": ["11px", { "lineHeight": "14px", "fontWeight": "500" }],
      },
      borderRadius: {
        "DEFAULT": "4px",
        "lg": "8px",
        "xl": "12px",
        "full": "9999px",
      },
    },
  },
  // Classes referencees depuis le code C (lignes de tables, badges,
  // barres de graphique crees dynamiquement) : Tailwind ne les verrait
  // pas sinon, car il ne scanne que les .tsx.
  safelist: [
    // Lignes de table generiques
    "flex", "flex-row", "flex-col", "items-center", "justify-between",
    "w-full", "flex-1", "border-b", "border-outline-variant",
    "px-4", "py-3", "px-6", "py-4", "py-2", "px-3", "px-2", "py-1",
    "mb-1", "mb-2", "mb-3", "mt-1", "mt-2", "ml-2", "mr-2", "mx-1",
    "text-body-md", "text-body-sm", "text-label-sm", "text-label-md",
    "text-headline-sm", "text-headline-md", "text-headline-lg",
    "text-on-surface", "text-secondary", "text-on-surface-variant",
    "text-primary", "text-error", "text-on-primary",
    "font-medium", "font-semibold", "font-bold",
    // Cellules avec largeurs fixes (5 colonnes)
    "w-1/5", "w-2/5", "w-1/4", "w-1/3", "w-1/2", "w-20", "w-24", "w-28", "w-32", "w-36", "w-40",
    "text-center", "text-right", "text-left",
    // Badges de statut
    "rounded-full", "rounded-lg", "rounded-xl", "rounded",
    "bg-vote-ok-bg", "text-vote-ok-text",
    "bg-vote-no-bg", "text-vote-no-text",
    "bg-vote-blanc-bg", "text-vote-blanc-text",
    "bg-status-active-bg", "text-status-active-text",
    "bg-surface-variant", "bg-surface-container", "bg-surface-container-low",
    "bg-surface-container-lowest", "bg-surface-container-high",
    "bg-primary", "bg-primary-fixed", "bg-surface-tint", "bg-error-container",
    // Cartes et barres du tableau de bord
    "border", "rounded-xl", "p-4", "p-6", "bg-primary-container",
    // Selection candidat (page vote)
    "border-primary", "border-outline-variant", "border-2",
    "bg-primary-fixed",
  ],
  corePlugins: [
    'backgroundSize',
    'backgroundColor',
    'backgroundImage',
    'backgroundPosition',
    'backgroundRepeat',
    'boxShadow',
    'boxSizing',
    'borderColor',
    'borderRadius',
    'borderStyle',
    'borderWidth',
    'content',
    'display',
    'flex',
    'flexBasis',
    'flexDirection',
    'flexGrow',
    'flexShrink',
    'flexWrap',
    'fontFamily',
    'fontSize',
    'fontWeight',
    'fontStyle',
    'margin',
    'padding',
    'position',
    'opacity',
    'justifyContent',
    'justifyItems',
    'alignContent',
    'alignItems',
    'height',
    'width',
    'maxWidth',
    'maxHeight',
    'minWidth',
    'minHeight',
    'textColor',
    'textAlign',
    'zIndex',
    'verticalAlign',
    'inset'
  ],
  plugins: [],
}
